config/routes.rb
Rails.application.routes.draw do
  
  get 'say/goodbye'

  get 'say/hello'

  get 'say/filenames'

  get 'say/filesearch'

  root 'say#hello'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
    before_action :time_now

    def goodbye
    end

    def hello
    end

    def filenames
        @files = Dir.glob('*')
    end

    def filesearch
    	query = params[:query]
	    files = Dir.glob('*').select {|s| s.include? "#{query}"}
    	render json: files
	end

    private

    def time_now
        @time = Time.now
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">

  	  	<div class="page-header">
    	    <h1>
     	       <%= yield(:title )%>
    	    </h1>
    	</div>

    	<%= yield %>

	</div>
  </body>
</html>

app/views/say/filenames.html.erb
<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">
            It is now <%=@time%>
        </h3>
    </div>

    <div class="panel-body">
    	<h1>Filenames</h1>
       	<p>
			<%= react_component('FileApp', files: @files) %>
		</p>

		<p>
			You can go back to
			<%= link_to "Hello", say_hello_path %>.
		</p>
    </div>

</div>

app/views/say/goodbye.html.erb
<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">
            It is now <%=@time%>
        </h3>
    </div>

    <div class="panel-body">
    	<h1>Goodbye</h1>
        <p>
			It was nice having you here
		</p>
		<p>
			Say <%= link_to "Hello", say_hello_path %> again
		</p>
    </div>
</div>

app/views/say/hello.html.erb
<% provide(:title, "Hello World from John Bedene") %>

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">
            It is now <%=@time%>
        </h3>
    </div>

    <div class="panel-body">
        <p>
            List of 
            <%=link_to "File Names", say_filenames_path %>!
        </p>
        <p>
            Time to say 
            <%=link_to "Goodbye", say_goodbye_path %>!
        </p>
    </div>

</div>